apiVersion: v2
appVersion: 1.0.0
description: unbound helm package
name: unbound
version: 1.0.5
kubeVersion: ">=1.16.0-0"
keywords:
  - unbound
home: https://github.com/nklmilojevic/helm-charts/tree/main/charts/unbound
sources:
  - https://github.com/klutchell/unbound
maintainers:
  - name: Nikola MilojeviÄ‡
    email: nikola@milojevic.me
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 3.3.0
